markdown: kramdown
pygments: true
github: [Repository metadata]


safe: true
lsi: false
source: your top-level directory
# Keep in mind that if you change the source setting, your pages may not build correctly. 
# GitHub Pages only considers source files in the top-level directory of a repository.

permalink: /:year/:month/:day/:title.html
# /:categories
highlighter: pygments
production_url: http://dfx.io
description_name: This world
description_blog: The blog
# image_url: /public/img/posts
future: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"

